#!/usr/bin/env python3
# =============================================================================
# generate_ontology_diagram.py
# -----------------------------------------------------------------------------
# Render the README's headline infographic as a PNG, straight from
# ontology/takt.ttl. Three panels, one story:
#
#   1  THE PLAN — the wagon x zone x takt grid planners already draw, with
#      numbered badges (1)-(5) marking what each part of the grid IS,
#   2  THE STACK — the vocabularies taktology reuses (colour-coded; the same
#      colours tag every alignment pill in panel 3),
#   3  THE VOCABULARY — the class graph. Badges match panel 1, alignment pills
#      are read from the Turtle (subClassOf / closeMatch / relatedMatch), and
#      each class card lists its datatype values.
#
# The picture is DATA-DRIVEN: the version string, term counts, per-class
# alignment pills, object-property arrows and per-class datatype chips are all
# read from the Turtle file. The *layout* (where each box sits) is authored
# once below; a validation step fails loudly if the ontology ever grows a class
# or property that the layout doesn't place, so the diagram can't silently
# drift out of sync.
#
# Run (regenerate after any ontology change / version bump):
#     python scripts/generate_ontology_diagram.py
#
# Output:
#     docs/diagrams/taktology-v{VERSION}.png   (one per version — history kept)
#     README.md <!-- ONTOLOGY-DIAGRAM --> block is repointed at the new file
#
# Dependencies: rdflib + Pillow (see scripts/requirements.txt). Fonts are
# bundled (scripts/assets/fonts) so output is byte-stable on Windows / Linux /
# macOS and in CI — no SVG rasteriser, Graphviz or browser needed.
# =============================================================================
from __future__ import annotations

import math
import sys
from pathlib import Path

try:
    import rdflib
    from rdflib import RDF, RDFS, OWL
    from rdflib.namespace import SKOS, Namespace
    from PIL import Image, ImageDraw, ImageFont, ImageFilter
except ImportError as exc:  # pragma: no cover - guidance only
    sys.exit(f"missing dependency: {exc}. Run: pip install -r scripts/requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
TTL = ROOT / "ontology" / "takt.ttl"
OUT_DIR = ROOT / "docs" / "diagrams"
README = ROOT / "README.md"
FONT_DIR = Path(__file__).resolve().parent / "assets" / "fonts"

TAKT = Namespace("https://w3id.org/taktology#")

# Namespace -> display prefix (drives the vocabulary colour-coding of pills).
NSMAP = {
    "https://w3id.org/taktology#": "takt",
    "https://dtc-ontology.cms.ed.tum.de/ontology/v2#": "dtc",
    "https://w3id.org/bot#": "bot",
    "http://w3id.org/topologicpy#": "top",
    "https://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL#": "ifc",
}

# --- README sync markers (the block between these is regenerated each run) ----
MARK_START = "<!-- ONTOLOGY-DIAGRAM:START (generated by scripts/generate_ontology_diagram.py — do not edit) -->"
MARK_END = "<!-- ONTOLOGY-DIAGRAM:END -->"
DISPLAY_WIDTH = 720   # README render width (px) — keep the picture from dominating the page


# =============================================================================
# 1. Parse the ontology
# =============================================================================
def localname(uri) -> str:
    s = str(uri)
    for sep in ("#", "/"):
        if sep in s:
            s = s.rsplit(sep, 1)[-1]
    return s


def qname(uri) -> str:
    s = str(uri)
    for ns, prefix in NSMAP.items():
        if s.startswith(ns):
            return f"{prefix}:{s[len(ns):]}"
    return localname(s)


def parse_ontology(path: Path):
    g = rdflib.Graph()
    g.parse(path, format="turtle")

    onto = next(g.subjects(RDF.type, OWL.Ontology))
    version = str(g.value(onto, OWL.versionInfo) or "0.0.0")

    def is_takt(s) -> bool:
        return str(s).startswith(str(TAKT))

    classes = {}
    for c in g.subjects(RDF.type, OWL.Class):
        if not is_takt(c):
            continue
        classes[localname(c)] = {
            "subClassOf": [localname(x) for x in g.objects(c, RDFS.subClassOf)],
            "subClassOfQ": [qname(x) for x in g.objects(c, RDFS.subClassOf)],
            "closeMatchQ": [qname(x) for x in g.objects(c, SKOS.closeMatch)],
            "relatedMatchQ": [qname(x) for x in g.objects(c, SKOS.relatedMatch)],
        }

    objprops = {}
    for p in g.subjects(RDF.type, OWL.ObjectProperty):
        if not is_takt(p):
            continue
        dom = [localname(x) for x in g.objects(p, RDFS.domain)]
        rng = [localname(x) for x in g.objects(p, RDFS.range)]
        objprops[localname(p)] = {
            "domain": dom[0] if dom else None,
            "range": rng[0] if rng else None,
            "subPropertyOf": [localname(x) for x in g.objects(p, RDFS.subPropertyOf)],
            "subPropertyOfQ": [qname(x) for x in g.objects(p, RDFS.subPropertyOf)],
        }

    dataprops = {}
    for p in g.subjects(RDF.type, OWL.DatatypeProperty):
        if not is_takt(p):
            continue
        dom = [localname(x) for x in g.objects(p, RDFS.domain)]
        dataprops[localname(p)] = {"domain": dom[0] if dom else None}

    return version, classes, objprops, dataprops


# =============================================================================
# 2. Layout (authored once; validated against the ontology below)
# =============================================================================
W, H = 1360, 1295  # logical canvas; rendered supersampled then downscaled

# --- panel 3: class cards. kind: takt / hero / ext. badge links to panel 1. ---
NODES = {
    "WagonType": dict(box=(76, 640, 420, 782), kind="takt", title="WagonType", badge=1,
                      note="fills DTC's missing type layer"),
    "Process": dict(box=(556, 616, 864, 698), kind="ext", title="dtc:Process",
                    lines=["the construction process (reused)"]),
    "TaktZone": dict(box=(936, 616, 1294, 774), kind="takt", title="TaktZone", badge=2),
    "TaktTask": dict(box=(548, 796, 872, 940), kind="hero", title="TaktTask", badge=3),
    "Crew": dict(box=(76, 1000, 420, 1118), kind="takt", title="Crew", badge=5),
    "Element": dict(box=(1006, 1002, 1294, 1118), kind="ext", title="bot:Element",
                    lines=["building elements (reused)", "quantities via TGraph / top:Quantity"]),
    "TaktGraph": dict(box=(540, 1002, 880, 1150), kind="takt", title="TaktGraph", badge=4),
}

# Which class each node represents (ext nodes map to no takt class).
NODE_CLASS = {k: k for k in NODES if NODES[k]["kind"] in ("takt", "hero")}

# Object-property arrows. `prop` ties the arrow to a takt object property (for
# validation); external=True edges are reused vocabulary (drawn dashed, green).
EDGES = [
    dict(prop="instantiates", src="TaktTask", dst="WagonType", label="instantiates", lpos=(452, 756)),
    dict(prop="partOfProcess", src="TaktTask", dst="Process", label="partOfProcess", lpos=(712, 748)),
    dict(prop="performedIn", src="TaktTask", dst="TaktZone", label="performedIn", lpos=(946, 790)),
    dict(prop="hasSuccessor", src="TaktTask", dst="TaktTask", kind="selfloop", side="left",
         label="hasSuccessor", lpos=(462, 836), sublabel="= the train", slpos=(462, 862)),
    dict(prop="performedBy", src="TaktTask", dst="Crew", label="performedBy", lpos=(438, 962)),
    dict(prop="actsOn", src="TaktTask", dst="Element", label="actsOn — the operand", lpos=(938, 946)),
    dict(prop=None, external=True, src="TaktGraph", dst="TaktTask", dashed=True, color="ext",
         label="dtc:hasProcess", lpos=(712, 976)),
    dict(prop=None, external=True, src="TaktZone", dst="Element",
         dashed=True, color="ext", label="bot:containsElement", lpos=(1152, 888)),
]


def validate(classes, objprops, dataprops):
    laid_classes = set(NODE_CLASS)
    missing_c = set(classes) - laid_classes
    if missing_c:
        sys.exit(f"ERROR: ontology classes not placed in NODES layout: {sorted(missing_c)}\n"
                 f"       Add a box for each, then re-run.")
    laid_props = {e["prop"] for e in EDGES if e.get("prop")}
    # A subproperty is covered when its parent is drawn (the parent arrow stands for it).
    covered = set(laid_props)
    for p, info in objprops.items():
        if info.get("subPropertyOf") and info["subPropertyOf"][0] in laid_props:
            covered.add(p)
    missing_p = set(objprops) - covered
    if missing_p:
        sys.exit(f"ERROR: ontology object properties not drawn as EDGES: {sorted(missing_p)}\n"
                 f"       Add an arrow for each (or make it a subproperty of a drawn one), then re-run.")
    # Every datatype property must land in a card: its domain's card, or (no
    # domain — plan-wide by convention, e.g. taktDuration) the TaktGraph card.
    for p, i in dataprops.items():
        home = i["domain"] or "TaktGraph"
        if home not in NODES:
            sys.exit(f"ERROR: datatype property '{p}' has domain '{i['domain']}' with no card in NODES.")
    phantom_c = laid_classes - set(classes)
    phantom_p = laid_props - set(objprops)
    if phantom_c or phantom_p:
        print(f"WARNING: layout references terms absent from the ontology: "
              f"classes={sorted(phantom_c)} props={sorted(phantom_p)}")


# =============================================================================
# 3. Derived content — alignment pills + datatype chips per card
# =============================================================================
def class_pills(name, info):
    """[(glyph+text, vocab)] pills for a takt class card, read from the ttl."""
    pills = []
    note = NODES[name].get("note")
    if note:
        pills.append((note, "note"))
    for q in info["subClassOfQ"]:
        pills.append(("⊑ " + q, q.split(":")[0]))
    for q in info["closeMatchQ"]:
        pills.append(("≈ " + q, q.split(":")[0]))
    for q in info["relatedMatchQ"]:
        pills.append(("~ " + q, q.split(":")[0]))
    return pills


def card_dataprops(name, dataprops):
    """Datatype chips shown inside a class card (domain-less -> TaktGraph)."""
    out = []
    for p, i in dataprops.items():
        home = i["domain"] or "TaktGraph"
        if home == name:
            out.append(p + (" (plan-wide)" if i["domain"] is None else ""))
    return sorted(out)


# =============================================================================
# 4. Rendering (Pillow, supersampled for anti-aliasing)
# =============================================================================
SS = 2  # supersample factor


def sc(v):
    return v * SS


# Vocabulary colour system — panel 2 slabs and every pill in panel 3 share it.
VOCAB = {
    "takt": dict(edge=(124, 110, 222), fill=(238, 236, 251), text=(74, 60, 176)),
    "dtc":  dict(edge=(46, 158, 116),  fill=(224, 243, 235), text=(22, 110, 78)),
    "bot":  dict(edge=(38, 142, 152),  fill=(220, 242, 244), text=(16, 108, 118)),
    "top":  dict(edge=(150, 92, 202),  fill=(243, 234, 250), text=(112, 58, 162)),
    "ifc":  dict(edge=(200, 140, 42),  fill=(252, 241, 221), text=(150, 100, 18)),
    "note": dict(edge=(150, 154, 168), fill=(240, 240, 245), text=(96, 100, 116)),
}

COL = dict(
    title=(92, 80, 190),          # readable on white AND dark GitHub themes
    subtitle=(118, 118, 132),
    panel_fill=(252, 252, 254),
    panel_edge=(216, 216, 232),
    panel_title=(92, 80, 190),
    ink=(46, 48, 68),
    muted=(112, 116, 134),
    faint=(150, 154, 170),
    takt_fill=(238, 236, 251),
    takt_edge=(124, 110, 222),
    takt_title=(40, 40, 74),
    hero_fill=(226, 220, 250),
    hero_edge=(102, 86, 220),
    ext_fill=(228, 244, 237),
    ext_edge=(46, 158, 116),
    ext_title=(24, 104, 74),
    ext_sub=(36, 130, 94),
    arrow=(124, 110, 222),
    arrow_ext=(46, 158, 116),
    edge_label=(88, 84, 134),
    pill=(246, 245, 252),         # halo pill behind edge labels
    pill_edge=(214, 210, 244),
    badge=(92, 80, 190),
    chip_fill=(255, 255, 255),
    chip_edge=(203, 206, 222),
    shadow=(40, 38, 90),
    grid_line=(210, 212, 226),
    readingA=(214, 96, 80),
    readingB=(84, 136, 210),
    buffer=(120, 126, 140),
    milestone=(178, 52, 40),
)

# Panel-1 wagons: id, label, colour (deliberately NOT the vocab colours above).
WAGONS = [("5.1", "framing", (78, 143, 217)),
          ("6.1", "MEP", (226, 158, 52)),
          ("7.1", "paint", (168, 104, 202))]
ZONES1 = ["A5:1", "B5:1", "C5"]
# grid[zone_row][slot] -> wagon index, or "buf"/"ms"/None
GRID1 = [[0, 1, 2, "buf", "ms"],
         [None, 0, 1, 2, None],
         [None, None, 0, 1, 2]]


def font_path(bold: bool) -> str:
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    p = FONT_DIR / name
    if p.exists():
        return str(p)
    try:  # fallback: borrow matplotlib's bundled copy
        import matplotlib
        mp = Path(matplotlib.__file__).parent / "mpl-data" / "fonts" / "ttf" / name
        if mp.exists():
            return str(mp)
    except Exception:
        pass
    sys.exit(f"font {name} not found in {FONT_DIR}")


def fnt(bold: bool, size: int):
    return ImageFont.truetype(font_path(bold), int(sc(size)))


def line(d, p, q, color, width):
    d.line([sc(p[0]), sc(p[1]), sc(q[0]), sc(q[1])], fill=color, width=int(sc(width)))


def polyline(d, pts, color, width):
    d.line([sc(c) for p in pts for c in p], fill=color, width=int(sc(width)), joint="curve")


def border_point(box, toward):
    x0, y0, x1, y1 = box
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    dx, dy = toward[0] - cx, toward[1] - cy
    if dx == 0 and dy == 0:
        return cx, cy
    sx = (x1 - cx) / dx if dx > 0 else ((x0 - cx) / dx if dx < 0 else math.inf)
    sy = (y1 - cy) / dy if dy > 0 else ((y0 - cy) / dy if dy < 0 else math.inf)
    s = min(sx, sy)
    return cx + dx * s, cy + dy * s


def arrowhead(d, tip, frm, color, size=13):
    ang = math.atan2(tip[1] - frm[1], tip[0] - frm[0])
    a1, a2 = ang + math.radians(152), ang - math.radians(152)
    p1 = (tip[0] + size * math.cos(a1), tip[1] + size * math.sin(a1))
    p2 = (tip[0] + size * math.cos(a2), tip[1] + size * math.sin(a2))
    d.polygon([sc(tip[0]), sc(tip[1]), sc(p1[0]), sc(p1[1]), sc(p2[0]), sc(p2[1])], fill=color)


def cubic(p0, p1, p2, p3, n=60):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**3 * p0[0] + 3 * u**2 * t * p1[0] + 3 * u * t**2 * p2[0] + t**3 * p3[0]
        y = u**3 * p0[1] + 3 * u**2 * t * p1[1] + 3 * u * t**2 * p2[1] + t**3 * p3[1]
        out.append((x, y))
    return out


def quad(p0, p1, p2, n=60):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**2 * p0[0] + 2 * u * t * p1[0] + t**2 * p2[0]
        y = u**2 * p0[1] + 2 * u * t * p1[1] + t**2 * p2[1]
        out.append((x, y))
    return out


def dashed_polyline(d, pts, color, width, dash=12, gap=8):
    draw_on, acc = True, 0.0
    for a, b in zip(pts, pts[1:]):
        seg = math.hypot(b[0] - a[0], b[1] - a[1])
        if seg == 0:
            continue
        ux, uy = (b[0] - a[0]) / seg, (b[1] - a[1]) / seg
        pos = 0.0
        while pos < seg:
            step = min((dash if draw_on else gap) - acc, seg - pos)
            x0, y0 = a[0] + ux * pos, a[1] + uy * pos
            x1, y1 = a[0] + ux * (pos + step), a[1] + uy * (pos + step)
            if draw_on:
                line(d, (x0, y0), (x1, y1), color, width)
            pos += step
            acc += step
            if acc >= (dash if draw_on else gap):
                draw_on = not draw_on
                acc = 0.0


def text_center(d, xy, text, font, color, halo=False, pad=(6, 2.5), radius=8):
    cx, cy = sc(xy[0]), sc(xy[1])
    if halo:
        bb = d.textbbox((cx, cy), text, font=font, anchor="mm")
        px, py = int(sc(pad[0])), int(sc(pad[1]))
        d.rounded_rectangle([bb[0] - px, bb[1] - py, bb[2] + px, bb[3] + py],
                            radius=int(sc(radius)), fill=COL["pill"], outline=COL["pill_edge"],
                            width=int(sc(1)))
    d.text((cx, cy), text, font=font, fill=color, anchor="mm")


def text_left(d, xy, text, font, color):
    d.text((sc(xy[0]), sc(xy[1])), text, font=font, fill=color, anchor="lm")


def badge(d, xy, n, f, r=11):
    cx, cy = xy
    d.ellipse([sc(cx - r), sc(cy - r), sc(cx + r), sc(cy + r)],
              fill=COL["badge"], outline=(255, 255, 255), width=int(sc(2)))
    d.text((sc(cx), sc(cy + 0.5)), str(n), font=f, fill=(255, 255, 255), anchor="mm")


def rounded(d, box, radius, fill, outline, width=1.6):
    d.rounded_rectangle([sc(box[0]), sc(box[1]), sc(box[2]), sc(box[3])],
                        radius=sc(radius), fill=fill, outline=outline, width=int(sc(width)))


def hatch(d, box, color, step=9, width=1.6):
    x0, y0, x1, y1 = box
    n = int(((x1 - x0) + (y1 - y0)) / step) + 1
    for i in range(n):
        ax = x0 + i * step
        sxp, syp = min(ax, x1), y0 + max(0, ax - x1)
        exp, eyp = x0 + max(0, i * step - (y1 - y0)), min(y0 + i * step, y1)
        if syp <= y1 and exp <= x1:
            line(d, (sxp, syp), (exp, eyp), color, width)


def pill_rows(d, cx, y, pills, f, max_w, gap=8, row_h=27):
    """Lay pills into centred rows within max_w. Returns the next free y."""
    pad = 9
    sizes = [(d.textlength(t, font=f) / SS + 2 * pad, t, v) for t, v in pills]
    rows, cur, cur_w = [], [], 0.0
    for w_, t, v in sizes:
        if cur and cur_w + gap + w_ > max_w:
            rows.append(cur)
            cur, cur_w = [], 0.0
        cur.append((w_, t, v))
        cur_w += (gap if len(cur) > 1 else 0) + w_
    if cur:
        rows.append(cur)
    for row in rows:
        total = sum(w_ for w_, *_ in row) + gap * (len(row) - 1)
        x = cx - total / 2
        for w_, t, v in row:
            c = VOCAB[v]
            rounded(d, (x, y - 11, x + w_, y + 11), 11, c["fill"], c["edge"], 1.4)
            text_center(d, (x + w_ / 2, y), t, f, c["text"])
            x += w_ + gap
        y += row_h
    return y


def render(version, classes, objprops, dataprops) -> Image.Image:
    # Transparent canvas so the PNG reads on any GitHub background (light OR dark).
    # NOTE the RGB of the fully-transparent pixels is a light neutral, NOT black:
    # LANCZOS downscaling mixes the RGB of transparent neighbours into text edges,
    # and a black base would put a dark fringe around every glyph drawn outside
    # the opaque panels.
    CLEAR = (246, 246, 250, 0)
    img = Image.new("RGBA", (int(sc(W)), int(sc(H))), CLEAR)

    P1 = (36, 122, 748, 552)      # panel 1 — the plan grid
    P2 = (768, 122, 1324, 552)    # panel 2 — the reuse stack
    P3 = (36, 574, 1324, 1198)    # panel 3 — the vocabulary graph

    # soft drop shadows under panels and cards
    shadow = Image.new("RGBA", img.size, COL["shadow"] + (0,))
    sd = ImageDraw.Draw(shadow)
    for box in (P1, P2, P3):
        sd.rounded_rectangle([sc(box[0]), sc(box[1] + 5), sc(box[2]), sc(box[3] + 9)],
                             radius=sc(18), fill=COL["shadow"] + (46,))
    shadow = shadow.filter(ImageFilter.GaussianBlur(sc(8)))
    img = Image.alpha_composite(img, shadow)
    d = ImageDraw.Draw(img)

    f_title = fnt(True, 36)
    f_sub = fnt(False, 18)
    f_ptitle = fnt(True, 17)
    f_card = fnt(True, 22)
    f_pill = fnt(False, 15)
    f_chip = fnt(False, 14)
    f_edge = fnt(False, 15)
    f_small = fnt(False, 14)
    f_tiny = fnt(False, 13)
    f_grid = fnt(True, 15)
    f_gridsub = fnt(False, 12)
    f_badge = fnt(True, 14)
    f_slab = fnt(True, 19)
    f_ext = fnt(False, 15)

    # ---- header (haloed: bare glyphs on the transparent canvas fuzz on dark themes)
    text_center(d, (W / 2, 44), f"taktology  v{version}", f_title, COL["title"],
                halo=True, pad=(18, 8), radius=16)
    text_center(d, (W / 2, 95),
                "takt production planning as a knowledge graph — the plan you draw is the graph you query",
                f_sub, COL["subtitle"], halo=True, pad=(10, 4), radius=11)

    for box in (P1, P2, P3):
        rounded(d, box, 18, COL["panel_fill"], COL["panel_edge"], 1.8)

    # ========================================================================
    # PANEL 1 — the takt plan grid
    # ========================================================================
    x0, y0, x1, y1 = P1
    text_left(d, (x0 + 26, y0 + 30), "1 · THE TAKT PLAN — what planners draw", f_ptitle, COL["panel_title"])
    # badge 4 tag, top-right: the whole grid IS the plan
    badge(d, (x1 - 36, y0 + 30), 4, f_badge, r=10)
    d.text((sc(x1 - 52), sc(y0 + 30)), "the whole grid", font=f_tiny, fill=COL["faint"], anchor="rm")

    # wagon legend (badge 1)
    wy = y0 + 66
    wx = x0 + 26
    badge(d, (wx + 10, wy), 1, f_badge)
    lead = "one colour = one trade's wagon:"
    text_left(d, (wx + 30, wy), lead, f_small, COL["ink"])
    wx += 30 + d.textlength(lead, font=f_small) / SS + 14
    for wid, wlab, wc in WAGONS:
        rounded(d, (wx, wy - 9, wx + 18, wy + 9), 5, wc, None)
        text_left(d, (wx + 24, wy), f"{wid} {wlab}", f_small, COL["muted"])
        wx += 24 + d.textlength(f"{wid} {wlab}", font=f_small) / SS + 16

    # grid geometry
    gx, gy = x0 + 128, y0 + 130
    cw, ch, cgap = 108, 56, 8
    cols = 5

    # column headers
    for c in range(cols):
        cxm = gx + c * (cw + cgap) + cw / 2
        text_center(d, (cxm, gy - 22), f"T{c + 1}", fnt(True, 15), COL["muted"])

    # rows
    for r, zname in enumerate(ZONES1):
        rym = gy + r * (ch + cgap) + ch / 2
        if r == 1:
            badge(d, (x0 + 38, rym), 2, f_badge)
        d.text((sc(x0 + 116), sc(rym)), zname, font=fnt(True, 15), fill=COL["ink"], anchor="rm")
        for c in range(cols):
            cx0 = gx + c * (cw + cgap)
            cell = (cx0, rym - ch / 2, cx0 + cw, rym + ch / 2)
            content = GRID1[r][c]
            if content is None:
                rounded(d, cell, 8, (247, 247, 250), COL["grid_line"], 1.2)
            elif content == "buf":
                rounded(d, cell, 8, (243, 244, 247), COL["buffer"], 1.4)
                hatch(d, (cell[0] + 3, cell[1] + 3, cell[2] - 3, cell[3] - 3), (204, 207, 218), 10, 1.4)
                text_center(d, (cx0 + cw / 2, rym), "buffer", f_gridsub, COL["buffer"])
            elif content == "ms":
                rounded(d, cell, 8, (250, 236, 233), COL["milestone"], 1.4)
                text_center(d, (cx0 + cw / 2, rym), "◆ handover", f_gridsub, COL["milestone"])
            else:
                wid, wlab, wc = WAGONS[content]
                rounded(d, cell, 8, tuple(min(255, v + int((255 - v) * 0.82)) for v in wc), wc, 1.6)
                d.rounded_rectangle([sc(cell[0]), sc(cell[1]), sc(cell[0] + 7), sc(cell[3])],
                                    radius=sc(3), fill=wc)
                # crew tag on one exemplar cell (badge 5)
                if (r, c) == (1, 2):
                    text_center(d, (cx0 + cw / 2 + 3, rym - 9), wid, f_grid, COL["ink"])
                    text_center(d, (cx0 + cw / 2 + 3, rym + 11), "crew SUB-07", f_gridsub, COL["muted"])
                    badge(d, (cell[2] - 2, cell[1] + 2), 5, f_badge, r=10)
                else:
                    text_center(d, (cx0 + cw / 2 + 3, rym), wid, f_grid, COL["ink"])
                if (r, c) == (0, 0):
                    badge(d, (cell[0] + 2, cell[1] + 2), 3, f_badge, r=10)

    # reading arrows over the grid
    rowy = lambda r: gy + r * (ch + cgap) + ch / 2
    colx = lambda c: gx + c * (cw + cgap)
    # Reading A: convoy in zone A5:1 — from 6.1@T2 to 7.1@T3
    ay = rowy(0)
    line(d, (colx(1) + cw + 1, ay), (colx(2) - 3, ay), COL["readingA"], 3.4)
    arrowhead(d, (colx(2) - 3, ay), (colx(1) + cw, ay), COL["readingA"], 11)
    # Reading B: 5.1 moves A5:1@T1 -> B5:1@T2
    bstart = (colx(0) + cw - 6, rowy(0) + ch / 2 - 4)
    bend = (colx(1) + 8, rowy(1) - ch / 2 + 4)
    line(d, bstart, bend, COL["readingB"], 3.4)
    arrowhead(d, bend, bstart, COL["readingB"], 11)

    # legends under the grid
    ly = gy + 3 * (ch + cgap) + 22
    lx = x0 + 26
    line(d, (lx, ly), (lx + 30, ly), COL["readingA"], 3.4)
    arrowhead(d, (lx + 32, ly), (lx, ly), COL["readingA"], 10)
    text_left(d, (lx + 42, ly), "Reading A · the convoy through one zone — hasSuccessorSameZone", f_small, COL["ink"])
    ly += 28
    line(d, (lx, ly), (lx + 30, ly), COL["readingB"], 3.4)
    arrowhead(d, (lx + 32, ly), (lx, ly), COL["readingB"], 10)
    text_left(d, (lx + 42, ly), "Reading B · one trade across the zones — hasSuccessorSameWagon", f_small, COL["ink"])
    ly += 30
    text_left(d, (lx, ly), "planned dates DERIVE:  planStart + (slot − 1) × taktDuration — the rhythm is the calendar",
              f_tiny, COL["muted"])

    # ========================================================================
    # PANEL 2 — the reuse stack
    # ========================================================================
    x0, y0, x1, y1 = P2
    text_left(d, (x0 + 26, y0 + 30), "2 · THE STACK — reused, not rebuilt", f_ptitle, COL["panel_title"])

    n_terms = len(classes) + len(objprops) + len(dataprops)
    slabs = [
        ("takt", "takt:", "wagon types · the rhythm · the plan-graph", f"{n_terms} terms", True),
        ("dtc", "dtc:", "DTC v2 — process · zones · crews · schedule", "⊑", False),
        ("bot", "bot:", "BOT — spatial topology: adjacency · containment", "⊑", False),
        ("top", "top:", "TopologicPy v0.2 — geometry · TGraph graphs", "⊑ ~", False),
        ("ifc", "ifc:", "IFC4 ifcOWL — industry interchange anchor", "≈", False),
    ]
    sy = y0 + 58
    sh, sgap = 56, 10
    for vocab, prefix, role, glyph, hero in slabs:
        c = VOCAB[vocab]
        box = (x0 + 26, sy, x1 - 26, sy + sh)
        rounded(d, box, 12, c["fill"], c["edge"], 2.6 if hero else 1.6)
        d.rounded_rectangle([sc(box[0]), sc(box[1]), sc(box[0] + 9), sc(box[3])], radius=sc(4), fill=c["edge"])
        text_left(d, (box[0] + 24, sy + sh / 2), prefix, f_slab, c["text"])
        text_left(d, (box[0] + 92, sy + sh / 2), role, f_small, COL["ink"] if hero else COL["muted"])
        d.text((sc(box[2] - 18), sc(sy + sh / 2)), glyph,
               font=fnt(True, 15 if hero else 17), fill=c["text"], anchor="rm")
        sy += sh + sgap
        if hero:
            # connective caption between the takt slab and the reused stack
            text_center(d, ((x0 + x1) / 2, sy - 1), "⌄   specializes by reference — no owl:imports   ⌄",
                        f_tiny, COL["faint"])
            sy += 16
    text_left(d, (x0 + 26, sy + 6), "these colours tag the pills below · pinned in alignments.lock.json",
              f_tiny, COL["faint"])

    # ========================================================================
    # PANEL 3 — the vocabulary graph
    # ========================================================================
    x0, y0, x1, y1 = P3
    text_left(d, (x0 + 26, y0 + 30),
              f"3 · THE VOCABULARY — {len(classes)} classes · {len(objprops)} relations · "
              f"{len(dataprops)} values  ·  every term cited to the research corpus", f_ptitle, COL["panel_title"])

    # card shadows
    cshadow = Image.new("RGBA", img.size, COL["shadow"] + (0,))
    csd = ImageDraw.Draw(cshadow)
    for n in NODES.values():
        bx0, by0, bx1, by1 = n["box"]
        csd.rounded_rectangle([sc(bx0), sc(by0 + 4), sc(bx1), sc(by1 + 6)],
                              radius=sc(16), fill=COL["shadow"] + (42,))
    cshadow = cshadow.filter(ImageFilter.GaussianBlur(sc(5)))
    img = Image.alpha_composite(img, cshadow)
    d = ImageDraw.Draw(img)

    # ---- edges (under the cards) ----
    for e in EDGES:
        sbox, dbox = NODES[e["src"]]["box"], NODES[e["dst"]]["box"]
        col = COL["arrow_ext"] if e.get("color") == "ext" else COL["arrow"]
        kind = e.get("kind", "straight")
        if kind == "selfloop":
            bx0, by0, bx1, by1 = sbox
            if e.get("side") == "left":
                left, cy = bx0, (by0 + by1) / 2
                pts = cubic((left + 2, cy - 16), (left - 60, cy - 50),
                            (left - 60, cy + 50), (left + 2, cy + 16))
            else:
                right, cy = bx1, (by0 + by1) / 2
                pts = cubic((right - 2, cy - 16), (right + 60, cy - 50),
                            (right + 60, cy + 50), (right - 2, cy + 16))
            polyline(d, pts, col, 3)
            arrowhead(d, pts[-1], pts[-4], col)
        elif kind == "curve":
            dc_ = (dbox[0] + dbox[2]) / 2, (dbox[1] + dbox[3]) / 2
            start = border_point(sbox, (sbox[0] - 120, sbox[3] + 160))
            end = border_point(dbox, (dbox[2] + 120, dc_[1] - 40))
            ctrl = ((start[0] + end[0]) / 2 + 130, (start[1] + end[1]) / 2 - 10)
            pts = quad(start, ctrl, end)
            dashed_polyline(d, pts, col, 3)
            arrowhead(d, pts[-1], pts[-4], col)
        else:
            sc_ = (sbox[0] + sbox[2]) / 2, (sbox[1] + sbox[3]) / 2
            dc_ = (dbox[0] + dbox[2]) / 2, (dbox[1] + dbox[3]) / 2
            start = border_point(sbox, dc_)
            end = border_point(dbox, sc_)
            if e.get("dashed"):
                dashed_polyline(d, [start, end], col, 3)
            else:
                line(d, start, end, col, 3)
            arrowhead(d, end, start, col)

    # ---- class cards ----
    for name, n in NODES.items():
        bx0, by0, bx1, by1 = n["box"]
        cx = (bx0 + bx1) / 2
        if n["kind"] == "ext":
            rounded(d, n["box"], 16, COL["ext_fill"], COL["ext_edge"], 2.2)
            text_center(d, (cx, by0 + 28), n["title"], f_card, COL["ext_title"])
            yy = by0 + 56
            for ln in n.get("lines", []):
                text_center(d, (cx, yy), ln, f_ext, COL["ext_sub"])
                yy += 22
            continue
        fill = COL["hero_fill"] if n["kind"] == "hero" else COL["takt_fill"]
        edge = COL["hero_edge"] if n["kind"] == "hero" else COL["takt_edge"]
        rounded(d, n["box"], 16, fill, edge, 2.8 if n["kind"] == "hero" else 2.2)
        text_center(d, (cx, by0 + 30), "takt:" + n["title"], f_card, COL["takt_title"])
        yy = by0 + 66
        yy = pill_rows(d, cx, yy, class_pills(name, classes[name]), f_pill, (bx1 - bx0) - 30)
        chips = card_dataprops(name, dataprops)
        if chips:
            ctext = "· " + "  · ".join(chips)
            wch = d.textlength(ctext, font=f_chip) / SS + 20
            rounded(d, (cx - wch / 2, yy - 12, cx + wch / 2, yy + 12), 12,
                    COL["chip_fill"], COL["chip_edge"], 1.3)
            text_center(d, (cx, yy), ctext, f_chip, COL["muted"])
        if n.get("badge"):
            badge(d, (bx0 + 3, by0 + 3), n["badge"], f_badge)

    # ---- edge labels ----
    for e in EDGES:
        text_center(d, e["lpos"], e["label"], f_edge, COL["edge_label"], halo=True)
        if e.get("sublabel"):
            text_center(d, e["slpos"], e["sublabel"], f_tiny, COL["muted"], halo=True)

    # ---- panel-3 legend ----
    text_center(d, ((x0 + x1) / 2, y1 - 22),
                "⊑ specializes    ≈ closeMatch    ~ relatedMatch    – – – reused external relation    "
                "①–⑤ the same thing as in panel 1",
                f_small, COL["muted"])

    # ---- footer -----------------------------------------------------------
    text_center(d, (W / 2, H - 66),
                "the payoff: one traversal   task → actsOn → element → quantity   — a spreadsheet cannot do that",
                fnt(True, 16), COL["title"], halo=True)
    text_center(d, (W / 2, H - 34),
                "every term carries dcterms:source → research/ corpus  ·  machine-checked by scripts/validate.py (SHACL + CQ queries)",
                f_tiny, COL["subtitle"], halo=True, pad=(9, 4), radius=10)

    # Force the RGB of transparent pixels to a light neutral before downscaling:
    # LANCZOS mixes the RGB of transparent neighbours into glyph/edge pixels, and
    # the composites above reset those to black, which would fringe every glyph
    # drawn outside the opaque panels.
    a = img.getchannel("A")
    neutral = Image.new("RGB", img.size, (246, 246, 250))
    rgb = Image.composite(img.convert("RGB"), neutral, a)
    img = Image.merge("RGBA", (*rgb.split(), a))

    return img.resize((W, H), Image.LANCZOS)


# =============================================================================
# 5. README sync
# =============================================================================
def update_readme(version, rel_png):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    alt = f"taktology v{version} — the takt plan, its reuse stack, and the vocabulary, in one infographic"
    block = (f'{MARK_START}\n\n'
             f'<p align="center">\n  <img src="{rel_png}" alt="{alt}" width="{DISPLAY_WIDTH}">\n</p>\n\n'
             f'{MARK_END}')
    if MARK_START in text and MARK_END in text:
        pre = text.split(MARK_START)[0]
        post = text.split(MARK_END, 1)[1]
        new = pre + block + post
    else:
        print("note: README has no <!-- ONTOLOGY-DIAGRAM --> markers; not modified.")
        return
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"updated README diagram block -> {rel_png}")
    else:
        print("README already up to date.")


# =============================================================================
def main():
    if not TTL.exists():
        sys.exit(f"ontology not found: {TTL}")
    version, classes, objprops, dataprops = parse_ontology(TTL)
    validate(classes, objprops, dataprops)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img = render(version, classes, objprops, dataprops)
    out = OUT_DIR / f"taktology-v{version}.png"
    img.save(out, "PNG", optimize=True)
    rel = out.relative_to(ROOT).as_posix()
    print(f"wrote {rel}  ({img.size[0]}x{img.size[1]}, "
          f"{len(classes)} classes, {len(objprops)} obj props, {len(dataprops)} data props)")

    update_readme(version, rel)


if __name__ == "__main__":
    main()
