#!/usr/bin/env python3
# =============================================================================
# generate_building_demo.py
# -----------------------------------------------------------------------------
# Emit examples/takt-building-demo.ttl — an anonymized multi-storey building
# fit-out takt plan, conforming to ontology/takt.ttl v0.5.0.
#
# The building: 3 storeys (L1-L3), each split into a West and an East takt zone
# (6 zones). A 5-wagon interiors train — framing, MEP rough-in, drywall, MEP
# fixtures, paint/floor — flows through the zones as a classic flowline: each
# zone starts one takt after the previous, so at any takt several wagons are on
# site in different zones. The wagons span the three disciplines a real fit-out
# touches (architectural + MEP), riding on a pre-existing structural shell
# (slabs + core, carried as building fabric).
#
#   slot(zone_position p, wagon w) = p + w        (1-based; p=0 for L1-West)
#
# The IRI scheme is deterministic so viz/index.html can attach geometry to the
# same elements without a shared data file:
#   zone     ex:zone_L{s}_{W|E}
#   operand  ex:{key}_L{s}_{W|E}   key in {part,duct,board,fixture,finish}
#   task     ex:task_L{s}_{W|E}_w{w}
#
# Run:  python scripts/generate_building_demo.py
# =============================================================================
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "examples" / "takt-building-demo.ttl"

STOREYS = [1, 2, 3]
ZONES = [("W", "West"), ("E", "East")]

# wagon: (order, label, trade, operand-key, discipline)
WAGONS = [
    (1, "Framing — metal stud partitions", "framing",   "part",    "architectural"),
    (2, "MEP rough-in — ducts & conduit",  "mep-rough", "duct",    "mep"),
    (3, "Drywall boarding",                "drywall",   "board",   "architectural"),
    (4, "MEP fixtures & terminals",        "mep-fix",   "fixture", "mep"),
    (5, "Paint & flooring",                "finish",    "finish",  "architectural"),
]

# operand-key -> human element noun
ELEM_NOUN = {
    "part":    "Stud partitions",
    "duct":    "Duct & conduit run",
    "board":   "Drywall boarding",
    "fixture": "MEP fixtures",
    "finish":  "Paint & floor finish",
}

TAKT_DURATION = "P7D"
PLAN_START = "2024-09-02"   # a Monday


def zone_positions():
    """Ordered (position, storey, zcode, zname) — the train's path, bottom-up."""
    p = 0
    for s in STOREYS:
        for zc, zn in ZONES:
            yield p, s, zc, zn
            p += 1


def main() -> None:
    L = []
    w = L.append
    w("# =============================================================================")
    w("# Building fit-out takt plan — anonymized 3-storey building, 6 takt zones")
    w("# GENERATED by scripts/generate_building_demo.py — do not edit by hand.")
    w("# Conforms to ontology/takt.ttl v0.5.0. Used by viz/index.html (the 3-layer")
    w("# visualizer: plan grid + knowledge graph + 3D building).")
    w("#")
    w("# A 5-wagon interiors train (framing -> MEP rough-in -> drywall -> MEP")
    w("# fixtures -> paint/floor) flows through West+East zones on L1-L3 as a")
    w("# flowline: slot(zone p, wagon w) = p + w. Structural slabs + core are")
    w("# pre-existing building fabric (bot:Element, no takt task). Element quantities")
    w("# / geometry travel as TGraph-style side data (viz/index.html), not core terms.")
    w("# =============================================================================")
    w("")
    w("@prefix takt: <https://w3id.org/taktology#> .")
    w("@prefix dtc:  <https://dtc-ontology.cms.ed.tum.de/ontology/v2#> .")
    w("@prefix bot:  <https://w3id.org/bot#> .")
    w("@prefix ex:   <https://w3id.org/taktology/examples/building#> .")
    w("@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .")
    w("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .")
    w("")

    positions = list(zone_positions())
    all_tasks = []
    for p, s, zc, zn in positions:
        for wo, *_ in WAGONS:
            all_tasks.append(f"ex:task_L{s}_{zc}_w{wo}")
    milestone = "ex:task_handover"

    # --- plan (TaktGraph) ---
    w("# --- THE PLAN — a takt:TaktGraph (top:KnowledgeGraph + dtc:ConstructionSchedule) ---")
    w("ex:plan a takt:TaktGraph ;")
    w('    rdfs:label "Building fit-out plan — Project Aspen (anonymized)"@en ;')
    w(f'    takt:taktDuration "{TAKT_DURATION}"^^xsd:duration ;')
    w(f'    takt:planStart    "{PLAN_START}"^^xsd:date ;')
    members = " ,\n                   ".join(all_tasks + [milestone])
    w(f"    dtc:hasProcess {members} .")
    w("")

    # --- process ---
    w("# --- The on-site fit-out PROCESS (TBS process axis; Ljung 2026) ---")
    w("ex:process_fitout a dtc:Process ;")
    w('    rdfs:label "Interior fit-out process"@en .')
    w("")

    # --- building + storeys ---
    w("# --- BUILDING / STOREYS (BOT topology) ---")
    storey_iris = " , ".join(f"ex:storey_L{s}" for s in STOREYS)
    w("ex:building a bot:Building ;")
    w('    rdfs:label "Project Aspen (anonymized)"@en ;')
    w(f"    bot:hasStorey {storey_iris} .")
    w("")
    for s in STOREYS:
        zs = " , ".join(f"ex:zone_L{s}_{zc}" for zc, _ in ZONES)
        w(f"ex:storey_L{s} a bot:Storey ;")
        w(f'    rdfs:label "Level {s}"@en ;')
        w(f"    bot:containsZone {zs} ;")
        w(f"    bot:containsElement ex:slab_L{s} .")
    w("")
    w("# Structural fabric carried in the graph (pre-existing shell; no takt task).")
    for s in STOREYS:
        w(f'ex:slab_L{s} a bot:Element ; rdfs:label "Floor slab, Level {s}"@en .')
    w('ex:core a bot:Element ; rdfs:label "Structural core (stairs + shafts)"@en .')
    w("")

    # --- zones + operands ---
    w("# --- TAKT ZONES + their trade operands (bot:containsElement) ---")
    for i, (p, s, zc, zn) in enumerate(positions):
        z = f"ex:zone_L{s}_{zc}"
        nxt = positions[i + 1] if i + 1 < len(positions) else None
        operands = [f"ex:{key}_L{s}_{zc}" for _, _, _, key, _ in WAGONS]
        w(f"{z} a takt:TaktZone ;")
        w(f'    rdfs:label "L{s} {zn} (Z{p + 1})" ;')
        if nxt:
            _, ns, nzc, _ = nxt
            w(f"    bot:adjacentZone ex:zone_L{ns}_{nzc} ;")
        contains = " ,\n                        ".join(operands + [f"ex:slab_L{s}", "ex:core"])
        w(f"    bot:containsElement {contains} .")
    w("")
    for p, s, zc, zn in positions:
        for _, _, _, key, disc in WAGONS:
            noun = ELEM_NOUN[key]
            w(f'ex:{key}_L{s}_{zc} a bot:Element ; rdfs:label "{noun}, L{s} {zn}"@en .')
    w("")

    # --- wagons + crews ---
    w("# --- WAGON TYPES (the train's consist) + planned crews ---")
    for wo, label, trade, key, disc in WAGONS:
        w(f"ex:wagon_{wo} a takt:WagonType ;")
        w(f'    rdfs:label "{wo} · {label}"@en ;')
        w(f'    takt:trade "{trade}" .')
    w("")
    for wo, label, trade, key, disc in WAGONS:
        w(f'ex:crew_{wo} a takt:Crew ; rdfs:label "SUB-{wo:02d}" .')
    w("")

    # --- tasks ---
    w("# =============================================================================")
    w("# THE GRID — 6 zones x 5 wagons = 30 cells, flowline slot = position + wagon")
    w("# =============================================================================")
    pos_by_wagon: dict[int, list] = {wo: [] for wo, *_ in WAGONS}
    for p, s, zc, zn in positions:
        for wo, *_ in WAGONS:
            pos_by_wagon[wo].append((p, s, zc))

    for p, s, zc, zn in positions:
        wagon_tasks = [f"ex:task_L{s}_{zc}_w{wo}" for wo, *_ in WAGONS]
        for idx, (wo, label, trade, key, disc) in enumerate(WAGONS):
            t = f"ex:task_L{s}_{zc}_w{wo}"
            slot = p + wo
            w(f"{t} a takt:TaktTask ;")
            w(f'    rdfs:label "{wo} @ L{s} {zn}" ;')
            w(f"    takt:instantiates ex:wagon_{wo} ;")
            w(f"    takt:performedIn  ex:zone_L{s}_{zc} ;")
            w(f"    takt:actsOn       ex:{key}_L{s}_{zc} ;")
            w(f"    takt:performedBy  ex:crew_{wo} ;")
            w(f"    takt:partOfProcess ex:process_fitout ;")
            w(f"    takt:slot         {slot} ;")
            # Reading A — next wagon, same zone
            if idx + 1 < len(WAGONS):
                w(f"    takt:hasSuccessorSameZone  ex:task_L{s}_{zc}_w{WAGONS[idx + 1][0]} ;")
            elif p == len(positions) - 1:
                # last wagon of the last zone -> handover milestone
                w(f"    takt:hasSuccessorSameZone  {milestone} ;")
            # Reading B — same wagon, next zone
            zone_seq = pos_by_wagon[wo]
            j = zone_seq.index((p, s, zc))
            if j + 1 < len(zone_seq):
                np, ns, nzc = zone_seq[j + 1]
                w(f"    takt:hasSuccessorSameWagon ex:task_L{ns}_{nzc}_w{wo} ;")
            # close statement (replace trailing ';' of last line with '.')
            L[-1] = L[-1].rstrip(" ;") + " ."
            w("")

    # --- milestone ---
    last_p, last_s, last_zc, last_zn = positions[-1]
    ms_slot = (len(positions) - 1) + len(WAGONS) + 1
    w("# Handover milestone — the last cell of the grid.")
    w(f"{milestone} a takt:TaktTask ;")
    w(f'    rdfs:label "Handover — L{last_s} {last_zn}" ;')
    w(f"    takt:performedIn ex:zone_L{last_s}_{last_zc} ;")
    w(f"    takt:partOfProcess ex:process_fitout ;")
    w(f"    takt:slot         {ms_slot} ;")
    w(f"    takt:isMilestone  true .")
    w("")

    OUT.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} — "
          f"{len(positions)} zones, {len(all_tasks)} wagon tasks + 1 milestone, "
          f"max slot {ms_slot}")


if __name__ == "__main__":
    main()
