#!/usr/bin/env python3
# =============================================================================
# generate_ontology_diagram.py
# -----------------------------------------------------------------------------
# Render the taktology ontology graph as a PNG, straight from ontology/takt.ttl.
#
# The picture is DATA-DRIVEN: the version string, the per-class DTC (subClassOf,
# shown ⊑) and IFC (closeMatch, shown ≈) alignments, the object-property arrows,
# the datatype-property footer and the term count are all read from the Turtle
# file. The *layout* (where each box sits) is authored once below; a validation
# step fails loudly if the ontology ever grows a class or object property that
# the layout doesn't place, so the diagram can't silently drift out of sync.
#
# Run (regenerate after any ontology change / version bump):
#     python scripts/generate_ontology_diagram.py
#
# Output:
#     docs/diagrams/taktology-v{VERSION}.png   (one per version — history kept)
#     README.md <!-- ONTOLOGY-DIAGRAM --> block is repointed at the new file
#
# Dependencies: rdflib + Pillow (see scripts/requirements.txt). Fonts are
# bundled (scripts/assets/fonts) so output is byte-stable on Windows / Linux /
# macOS and in CI — no SVG rasteriser, Graphviz or browser needed.
# =============================================================================
from __future__ import annotations

import math
import sys
from pathlib import Path

try:
    import rdflib
    from rdflib import RDF, RDFS, OWL
    from rdflib.namespace import SKOS, Namespace
    from PIL import Image, ImageDraw, ImageFont, ImageFilter
except ImportError as exc:  # pragma: no cover - guidance only
    sys.exit(f"missing dependency: {exc}. Run: pip install -r scripts/requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
TTL = ROOT / "ontology" / "takt.ttl"
OUT_DIR = ROOT / "docs" / "diagrams"
README = ROOT / "README.md"
FONT_DIR = Path(__file__).resolve().parent / "assets" / "fonts"

TAKT = Namespace("https://w3id.org/taktology#")

# --- README sync markers (the block between these is regenerated each run) ----
MARK_START = "<!-- ONTOLOGY-DIAGRAM:START (generated by scripts/generate_ontology_diagram.py — do not edit) -->"
MARK_END = "<!-- ONTOLOGY-DIAGRAM:END -->"
DISPLAY_WIDTH = 720   # README render width (px) — keep the picture from dominating the page


# =============================================================================
# 1. Parse the ontology
# =============================================================================
def localname(uri) -> str:
    s = str(uri)
    for sep in ("#", "/"):
        if sep in s:
            s = s.rsplit(sep, 1)[-1]
    return s


def parse_ontology(path: Path):
    g = rdflib.Graph()
    g.parse(path, format="turtle")

    onto = next(g.subjects(RDF.type, OWL.Ontology))
    version = str(g.value(onto, OWL.versionInfo) or "0.0.0")

    def is_takt(s) -> bool:
        return str(s).startswith(str(TAKT))

    classes = {}
    for c in g.subjects(RDF.type, OWL.Class):
        if not is_takt(c):
            continue
        classes[localname(c)] = {
            "subClassOf": [localname(x) for x in g.objects(c, RDFS.subClassOf)],
            "closeMatch": [localname(x) for x in g.objects(c, SKOS.closeMatch)],
            "seeAlso": [localname(x) for x in g.objects(c, RDFS.seeAlso)],
        }

    objprops = {}
    for p in g.subjects(RDF.type, OWL.ObjectProperty):
        if not is_takt(p):
            continue
        dom = [localname(x) for x in g.objects(p, RDFS.domain)]
        rng = [localname(x) for x in g.objects(p, RDFS.range)]
        objprops[localname(p)] = {
            "domain": dom[0] if dom else None,
            "range": rng[0] if rng else None,
            "subPropertyOf": [localname(x) for x in g.objects(p, RDFS.subPropertyOf)],
            "seeAlso": [localname(x) for x in g.objects(p, RDFS.seeAlso)],
        }

    dataprops = {}
    for p in g.subjects(RDF.type, OWL.DatatypeProperty):
        if not is_takt(p):
            continue
        dom = [localname(x) for x in g.objects(p, RDFS.domain)]
        dataprops[localname(p)] = {"domain": dom[0] if dom else None}

    return version, classes, objprops, dataprops


# =============================================================================
# 2. Layout (authored once; validated against the ontology below)
# =============================================================================
W, H = 1300, 950  # logical canvas; rendered supersampled then downscaled

# kind: takt = takt class, hero = the central takt class, ext = external node
NODES = {
    "WagonType": dict(box=(70, 138, 398, 262), kind="takt", title="WagonType"),
    "Process": dict(box=(478, 138, 818, 262), kind="ext", title="dtc:Process",
                    lines=["≈ IfcProcess", "construction process"]),
    "TaktZone": dict(box=(812, 138, 1150, 262), kind="takt", title="TaktZone"),
    "TaktTask": dict(box=(478, 392, 818, 488), kind="hero", title="TaktTask", compact=True),
    "Crew": dict(box=(70, 632, 398, 758), kind="takt", title="Crew"),
    "Element": dict(box=(478, 650, 772, 776), kind="ext", title="top:Element",
                    lines=["⊑ bot:Element  ≈ IfcElement", "geometry · top:area"]),
    "TaktTime": dict(box=(812, 632, 1150, 758), kind="takt", title="TaktTime"),
}

# Per-node first-line override where we want a note instead of the raw alignment
# (WagonType deliberately has no DTC parent — say so rather than show seeAlso).
NODE_NOTE = {"WagonType": "— no DTC type layer"}

# Known external super-classes (NOT asserted in takt.ttl — these are the upstream
# ontologies' own alignments, shown so the BOT/IFC anchor is visible on the graph).
EXT_SUPER = {"FunctionalZone": "bot:Zone"}   # top:FunctionalZone ⊑ bot:Zone (TopologicPy → BOT)

# Which class each node represents (ext nodes map to no takt class).
NODE_CLASS = {k: k for k in NODES if NODES[k]["kind"] in ("takt", "hero")}

# Object-property arrows. `prop` ties the arrow to a takt object property (for
# validation); external=True edges are context (not takt terms).
EDGES = [
    dict(prop="instantiates", src="TaktTask", dst="WagonType", label="instantiates", lpos=(440, 332)),
    dict(prop="partOfProcess", src="TaktTask", dst="Process", label="partOfProcess", lpos=(648, 330)),
    dict(prop="performedIn", src="TaktTask", dst="TaktZone", label="performedIn", lpos=(856, 332)),
    dict(prop="hasSuccessor", src="TaktTask", dst="TaktTask", kind="selfloop", side="right",
         label="hasSuccessor", lpos=(912, 440)),
    dict(prop="performedBy", src="TaktTask", dst="Crew", label="performedBy", lpos=(452, 602)),
    dict(prop="actsOn", src="TaktTask", dst="Element", label="actsOn", lpos=(648, 606)),
    dict(prop="hasTaktTime", src="TaktTask", dst="TaktTime", label="hasTaktTime", lpos=(846, 602)),
    dict(prop=None, external=True, src="TaktZone", dst="Element", kind="curve",
         dashed=True, color="ext", label="containsElement", lpos=(1012, 470)),
]


def validate(classes, objprops):
    laid_classes = set(NODE_CLASS)
    missing_c = set(classes) - laid_classes
    if missing_c:
        sys.exit(f"ERROR: ontology classes not placed in NODES layout: {sorted(missing_c)}\n"
                 f"       Add a box for each, then re-run.")
    laid_props = {e["prop"] for e in EDGES if e.get("prop")}
    missing_p = set(objprops) - laid_props
    if missing_p:
        sys.exit(f"ERROR: ontology object properties not drawn as EDGES: {sorted(missing_p)}\n"
                 f"       Add an arrow for each, then re-run.")
    phantom_c = laid_classes - set(classes)
    phantom_p = laid_props - set(objprops)
    if phantom_c or phantom_p:
        print(f"WARNING: layout references terms absent from the ontology: "
              f"classes={sorted(phantom_c)} props={sorted(phantom_p)}")


# =============================================================================
# 3. Derive the text content from the parsed ontology
# =============================================================================
def node_alignment_lines(name, info):
    """The 1-2 grey alignment lines shown inside a takt box (⊑ DTC, ≈ IFC)."""
    lines = []
    if name in NODE_NOTE:
        lines.append(NODE_NOTE[name])
    elif info["subClassOf"]:
        # prefer a parent with a known external super-chain (FunctionalZone ⊑ bot:Zone)
        parents = info["subClassOf"]
        parent = next((p for p in parents if p in EXT_SUPER), parents[0])
        chain = "⊑ " + parent
        if parent in EXT_SUPER:
            chain += " ⊑ " + EXT_SUPER[parent]
        lines.append(chain)                              # ⊑ subClassOf (+ external super)
    elif info["seeAlso"]:
        lines.append("seeAlso " + "/".join(info["seeAlso"]))
    if info["closeMatch"]:
        lines.append("≈ " + info["closeMatch"][0])       # ≈ closeMatch
    return lines


def footer_objprops(objprops):
    reused = [f"{p} ⊑ {i['subPropertyOf'][0]}" for p, i in objprops.items() if i["subPropertyOf"]]
    seealso = [p for p, i in objprops.items() if not i["subPropertyOf"] and i["seeAlso"]]
    parts = list(reused)
    if seealso:
        parts.append(" / ".join(seealso) + " seeAlso DTC (reified)")
    return "Object props reuse DTC:  " + "  ·  ".join(parts)


def footer_dataprops(dataprops):
    order, groups = [], {}
    for p, i in dataprops.items():
        d = i["domain"] or "?"
        if d not in groups:
            groups[d] = []
            order.append(d)
    for p, i in dataprops.items():
        groups[i["domain"] or "?"].append(p)
    return "Datatypes — " + "   |   ".join(f"{d}: " + " · ".join(groups[d]) for d in order)


# =============================================================================
# 4. Rendering (Pillow, supersampled for anti-aliasing)
# =============================================================================
SS = 2  # supersample factor


def sc(v):
    return v * SS


COL = dict(
    bg=(255, 255, 255),          # kept only for optional flat-background previews
    title=(92, 80, 190),         # medium indigo — readable on white AND dark themes
    subtitle=(118, 118, 132),    # mid neutral — balanced contrast on both themes
    takt_fill=(238, 236, 251),
    takt_edge=(124, 110, 222),
    takt_title=(40, 40, 74),
    takt_sub=(108, 92, 226),
    hero_fill=(200, 192, 240),
    hero_edge=(102, 86, 220),
    ext_fill=(224, 243, 235),
    ext_edge=(46, 158, 116),
    ext_title=(24, 104, 74),
    ext_sub=(36, 138, 98),
    arrow=(124, 110, 222),
    arrow_ext=(46, 158, 116),
    edge_label=(88, 84, 134),     # dark slate-purple — sits on the light pill below
    pill=(240, 239, 250),         # opaque light pill behind edge labels (reads on light + dark)
    pill_edge=(214, 210, 244),
    footer=(118, 118, 132),
    shadow=(40, 38, 90),
)


def font_path(bold: bool) -> str:
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    p = FONT_DIR / name
    if p.exists():
        return str(p)
    try:  # fallback: borrow matplotlib's bundled copy
        import matplotlib
        mp = Path(matplotlib.__file__).parent / "mpl-data" / "fonts" / "ttf" / name
        if mp.exists():
            return str(mp)
    except Exception:
        pass
    sys.exit(f"font {name} not found in {FONT_DIR}")


def fnt(bold: bool, size: int):
    return ImageFont.truetype(font_path(bold), int(sc(size)))


def line(d, p, q, color, width):
    d.line([sc(p[0]), sc(p[1]), sc(q[0]), sc(q[1])], fill=color, width=int(sc(width)))


def polyline(d, pts, color, width):
    d.line([sc(c) for p in pts for c in p], fill=color, width=int(sc(width)), joint="curve")


def border_point(box, toward):
    x0, y0, x1, y1 = box
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    dx, dy = toward[0] - cx, toward[1] - cy
    if dx == 0 and dy == 0:
        return cx, cy
    sx = (x1 - cx) / dx if dx > 0 else ((x0 - cx) / dx if dx < 0 else math.inf)
    sy = (y1 - cy) / dy if dy > 0 else ((y0 - cy) / dy if dy < 0 else math.inf)
    s = min(sx, sy)
    return cx + dx * s, cy + dy * s


def arrowhead(d, tip, frm, color, size=15):
    ang = math.atan2(tip[1] - frm[1], tip[0] - frm[0])
    a1, a2 = ang + math.radians(152), ang - math.radians(152)
    p1 = (tip[0] + size * math.cos(a1), tip[1] + size * math.sin(a1))
    p2 = (tip[0] + size * math.cos(a2), tip[1] + size * math.sin(a2))
    d.polygon([sc(tip[0]), sc(tip[1]), sc(p1[0]), sc(p1[1]), sc(p2[0]), sc(p2[1])], fill=color)


def cubic(p0, p1, p2, p3, n=60):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**3 * p0[0] + 3 * u**2 * t * p1[0] + 3 * u * t**2 * p2[0] + t**3 * p3[0]
        y = u**3 * p0[1] + 3 * u**2 * t * p1[1] + 3 * u * t**2 * p2[1] + t**3 * p3[1]
        out.append((x, y))
    return out


def quad(p0, p1, p2, n=60):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**2 * p0[0] + 2 * u * t * p1[0] + t**2 * p2[0]
        y = u**2 * p0[1] + 2 * u * t * p1[1] + t**2 * p2[1]
        out.append((x, y))
    return out


def dashed_polyline(d, pts, color, width, dash=12, gap=8):
    draw_on, acc = True, 0.0
    for a, b in zip(pts, pts[1:]):
        seg = math.hypot(b[0] - a[0], b[1] - a[1])
        if seg == 0:
            continue
        ux, uy = (b[0] - a[0]) / seg, (b[1] - a[1]) / seg
        pos = 0.0
        while pos < seg:
            step = min((dash if draw_on else gap) - acc, seg - pos)
            x0, y0 = a[0] + ux * pos, a[1] + uy * pos
            x1, y1 = a[0] + ux * (pos + step), a[1] + uy * (pos + step)
            if draw_on:
                line(d, (x0, y0), (x1, y1), color, width)
            pos += step
            acc += step
            if acc >= (dash if draw_on else gap):
                draw_on = not draw_on
                acc = 0.0


def text_center(d, xy, text, font, color, halo=False):
    # halo = a small rounded "pill" behind the label so it reads cleanly where it
    # crosses an arrow, on the transparent canvas, under either GitHub theme.
    cx, cy = sc(xy[0]), sc(xy[1])
    if halo:
        bb = d.textbbox((cx, cy), text, font=font, anchor="mm")
        px, py = int(sc(6)), int(sc(2.5))
        d.rounded_rectangle([bb[0] - px, bb[1] - py, bb[2] + px, bb[3] + py],
                            radius=int(sc(8)), fill=COL["pill"], outline=COL["pill_edge"],
                            width=int(sc(1)))
    d.text((cx, cy), text, font=font, fill=color, anchor="mm")


def render(version, classes, objprops, dataprops) -> Image.Image:
    # Transparent canvas so the PNG reads on any GitHub background (light OR dark).
    img = Image.new("RGBA", (int(sc(W)), int(sc(H))), (0, 0, 0, 0))

    # soft drop shadows under every box
    shadow = Image.new("RGBA", img.size, (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    for n in NODES.values():
        x0, y0, x1, y1 = n["box"]
        sd.rounded_rectangle([sc(x0), sc(y0 + 5), sc(x1), sc(y1 + 8)],
                             radius=sc(20), fill=COL["shadow"] + (55,))
    shadow = shadow.filter(ImageFilter.GaussianBlur(sc(7)))
    img = Image.alpha_composite(img, shadow)
    d = ImageDraw.Draw(img)

    f_title = fnt(True, 30)
    f_sub = fnt(False, 17)
    f_node = fnt(True, 23)
    f_align = fnt(False, 16)
    f_edge = fnt(False, 16)
    f_foot = fnt(False, 14)
    f_leg = fnt(False, 15)

    # ---- title + subtitle -----------------------------------------------
    text_center(d, (W / 2, 42), f"taktology v{version} — minimal core ontology", f_title, COL["title"])
    n_terms = len(classes) + len(objprops) + len(dataprops)
    text_center(d, (W / 2, 80),
                f"{n_terms} terms · takt: specializes DTC (⊑) and closeMatch IFC (≈)",
                f_sub, COL["subtitle"])

    # ---- edges (under the boxes) ----------------------------------------
    for e in EDGES:
        sbox, dbox = NODES[e["src"]]["box"], NODES[e["dst"]]["box"]
        col = COL["arrow_ext"] if e.get("color") == "ext" else COL["arrow"]
        kind = e.get("kind", "straight")
        if kind == "selfloop":
            x0, y0, x1, y1 = sbox
            if e.get("side") == "right":          # arc off the right flank (keeps the top clear)
                right, cy = x1, (y0 + y1) / 2
                pts = cubic((right - 2, cy - 16), (right + 64, cy - 52),
                            (right + 64, cy + 52), (right - 2, cy + 16))
            else:
                cx, top = (x0 + x1) / 2, y0
                pts = cubic((cx - 24, top + 2), (cx - 70, top - 78),
                            (cx + 70, top - 78), (cx + 24, top + 2))
            polyline(d, pts, col, 3)
            arrowhead(d, pts[-1], pts[-4], col)
        elif kind == "curve":
            sc_ = (sbox[0] + sbox[2]) / 2, (sbox[1] + sbox[3]) / 2
            dc_ = (dbox[0] + dbox[2]) / 2, (dbox[1] + dbox[3]) / 2
            start = border_point(sbox, dc_)
            end = border_point(dbox, (dbox[2] + 80, dc_[1]))  # arrive at right flank
            ctrl = ((start[0] + end[0]) / 2 + 120, (start[1] + end[1]) / 2 + 30)
            pts = quad(start, ctrl, end)
            dashed_polyline(d, pts, col, 3)
            arrowhead(d, pts[-1], pts[-4], col)
        else:
            sc_ = (sbox[0] + sbox[2]) / 2, (sbox[1] + sbox[3]) / 2
            dc_ = (dbox[0] + dbox[2]) / 2, (dbox[1] + dbox[3]) / 2
            start = border_point(sbox, dc_)
            end = border_point(dbox, sc_)
            line(d, start, end, col, 3)
            arrowhead(d, end, start, col)

    # ---- node boxes ------------------------------------------------------
    for name, n in NODES.items():
        x0, y0, x1, y1 = n["box"]
        cx = (x0 + x1) / 2
        if n["kind"] == "ext":
            fill, edge, tcol, scol = COL["ext_fill"], COL["ext_edge"], COL["ext_title"], COL["ext_sub"]
        elif n["kind"] == "hero":
            fill, edge, tcol, scol = COL["hero_fill"], COL["hero_edge"], COL["takt_title"], COL["takt_sub"]
        else:
            fill, edge, tcol, scol = COL["takt_fill"], COL["takt_edge"], COL["takt_title"], COL["takt_sub"]
        d.rounded_rectangle([sc(x0), sc(y0), sc(x1), sc(y1)], radius=sc(20),
                            fill=fill, outline=edge, width=int(sc(2.4)))

        if n["kind"] == "ext":
            sublines = n.get("lines", [])
        else:
            sublines = node_alignment_lines(NODE_CLASS[name], classes[NODE_CLASS[name]])
        if n.get("compact") and len(sublines) > 1:
            sublines = ["    ".join(sublines)]   # one tight line so the box can be shorter

        if sublines:
            text_center(d, (cx, y0 + 42), n["title"], f_node, tcol)
            ys = y0 + 78
            for ln in sublines:
                text_center(d, (cx, ys), ln, f_align, scol)
                ys += 28
        else:
            text_center(d, (cx, (y0 + y1) / 2), n["title"], f_node, tcol)

    # ---- edge labels (on top, with white halo) --------------------------
    for e in EDGES:
        text_center(d, e["lpos"], e["label"], f_edge, COL["edge_label"], halo=True)

    # ---- footer text -----------------------------------------------------
    text_center(d, (W / 2, 818), footer_objprops(objprops), f_foot, COL["footer"])
    text_center(d, (W / 2, 844), footer_dataprops(dataprops), f_foot, COL["footer"])

    # ---- legend ----------------------------------------------------------
    ly = 898
    r = 9
    items_w = 0  # draw centered: compute total width first
    segs = [("dot", COL["takt_edge"], COL["takt_fill"], "takt: class"),
            ("ring", COL["ext_edge"], None, "external (DTC / IFC / top:)"),
            ("txt", None, None, "⊑ subClassOf   ·   ≈ closeMatch")]
    gap = 34
    widths = []
    for kind, _, _, label in segs:
        w = d.textlength(label, font=f_leg) / SS + (28 if kind != "txt" else 0)
        widths.append(w)
    total = sum(widths) + gap * (len(segs) - 1)
    x = W / 2 - total / 2
    for (kind, ec, fc, label), w in zip(segs, widths):
        if kind == "dot":
            d.ellipse([sc(x), sc(ly - r), sc(x + 2 * r), sc(ly + r)], fill=fc, outline=ec, width=int(sc(2)))
            d.text((sc(x + 2 * r + 8), sc(ly)), label, font=f_leg, fill=COL["footer"], anchor="lm")
        elif kind == "ring":
            d.ellipse([sc(x), sc(ly - r), sc(x + 2 * r), sc(ly + r)], fill=fc, outline=ec, width=int(sc(2)))
            d.text((sc(x + 2 * r + 8), sc(ly)), label, font=f_leg, fill=COL["footer"], anchor="lm")
        else:
            d.text((sc(x), sc(ly)), label, font=f_leg, fill=COL["footer"], anchor="lm")
        x += w + gap

    return img.resize((W, H), Image.LANCZOS)


# =============================================================================
# 5. README sync
# =============================================================================
def update_readme(version, rel_png):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    alt = f"taktology v{version} — minimal core ontology graph"
    block = (f'{MARK_START}\n\n'
             f'<p align="center">\n  <img src="{rel_png}" alt="{alt}" width="{DISPLAY_WIDTH}">\n</p>\n\n'
             f'{MARK_END}')
    if MARK_START in text and MARK_END in text:
        pre = text.split(MARK_START)[0]
        post = text.split(MARK_END, 1)[1]
        new = pre + block + post
    else:
        print("note: README has no <!-- ONTOLOGY-DIAGRAM --> markers; not modified.")
        return
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"updated README diagram block -> {rel_png}")
    else:
        print("README already up to date.")


# =============================================================================
def main():
    if not TTL.exists():
        sys.exit(f"ontology not found: {TTL}")
    version, classes, objprops, dataprops = parse_ontology(TTL)
    validate(classes, objprops)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img = render(version, classes, objprops, dataprops)
    out = OUT_DIR / f"taktology-v{version}.png"
    img.save(out, "PNG", optimize=True)
    rel = out.relative_to(ROOT).as_posix()
    print(f"wrote {rel}  ({img.size[0]}x{img.size[1]}, "
          f"{len(classes)} classes, {len(objprops)} obj props, {len(dataprops)} data props)")

    update_readme(version, rel)


if __name__ == "__main__":
    main()
