#!/usr/bin/env python3
# =============================================================================
# generate_takt_scheme.py
# -----------------------------------------------------------------------------
# Render the worked example as a normal takt-planning scheme (a flowline /
# takt board), straight from examples/takt-flowline-demo.csv.
#
# A takt scheme is the classic coloured grid: takt ZONES down the side, takt
# WEEKS across the top, and one coloured cell per takt task — the same wagon
# walking zone-to-zone makes the diagonal "train". The grid is DATA-DRIVEN
# (zones, weeks and which wagon sits in each cell all come from the CSV); the
# WAGONS table below is the authored legend (label + colour per wagon), and a
# validation step fails loudly if the CSV ever uses a wagon the table doesn't
# define — so the picture can't silently drift out of sync with the data.
#
# Run (regenerate after the demo plan changes):
#     python scripts/generate_takt_scheme.py
#
# Output:
#     docs/diagrams/takt-scheme-demo.png   (transparent — reads on light/dark)
#     README.md <!-- TAKT-SCHEME --> block is repointed (inserted just below the
#     ontology diagram block if it doesn't exist yet)
#
# Dependencies: Pillow (see scripts/requirements.txt). Fonts are bundled
# (scripts/assets/fonts) so output is byte-stable across OSes and in CI.
# =============================================================================
from __future__ import annotations

import csv
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as exc:  # pragma: no cover - guidance only
    sys.exit(f"missing dependency: {exc}. Run: pip install -r scripts/requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "examples" / "takt-flowline-demo.csv"
OUT = ROOT / "docs" / "diagrams" / "takt-scheme-demo.png"
README = ROOT / "README.md"
FONT_DIR = Path(__file__).resolve().parent / "assets" / "fonts"

# README sync markers (this block is regenerated each run); the scheme is placed
# directly below the ontology diagram if its markers aren't in the file yet.
MARK_START = "<!-- TAKT-SCHEME:START (generated by scripts/generate_takt_scheme.py — do not edit) -->"
MARK_END = "<!-- TAKT-SCHEME:END -->"
ONTOLOGY_END = "<!-- ONTOLOGY-DIAGRAM:END -->"

# The worked A-Box (examples/takt-flowline-demo-b5-1.ttl) models exactly this
# cell — highlight it so the two example artifacts line up.
CALLOUT_ZONE, CALLOUT_WEEK = "B5:1", "T04"

# --- The wagon catalog (label + colour per wagon) ----------------------------
# Source: examples/takt-flowline-demo.md §1 "The takt train (wagon catalog)".
# Order here is the legend order. Colours are grouped by trade family so the
# flowline reads as related bands (drywall = blues, electrical = violets, …).
WAGONS = {
    "3":    ("Survey & layout",          "#5B6B7A"),
    "5.1":  ("Drywall — 1st-side board", "#2E78C7"),
    "5.2":  ("MEP in-wall (conduit)",    "#17A2A2"),
    "5.3":  ("Drywall — close-up",       "#5BA3E0"),
    "6.1":  ("Painting — fill & coat",   "#E8913A"),
    "7":    ("Suspended ceiling",        "#4FA85C"),
    "8":    ("Sprinkler",                "#D64550"),
    "9":    ("Ventilation",              "#34B6D6"),
    "10":   ("Plumbing",                 "#3F51B5"),
    "11.1": ("Electrical — trays",       "#7E57C2"),
    "12.1": ("Electrical — cabling",     "#9C6ADE"),
    "13":   ("Electrical — data/fire",   "#6A4CA8"),
    "14":   ("BMS / IT cabling",         "#C94FB0"),
    "17.1": ("Paint & tile — wet rooms", "#E76A8D"),
    "18":   ("Flooring",                 "#A9744F"),
    "20.1": ("Joinery",                  "#B0A14E"),
    "21":   ("MEP/BMS fit-out",          "#2BB3A3"),
    "22":   ("Commissioning",            "#E0B33A"),
    "23":   ("Cleaning & handover",      "#7C9A6B"),
}

# --- Theme-agnostic ink (readable on white AND dark GitHub backgrounds) -------
INK_TITLE = (92, 80, 190)       # medium indigo
INK = (118, 118, 132)           # mid neutral for labels
GRID = (150, 150, 162, 90)      # faint lattice
GUIDE = (150, 150, 162, 60)     # even fainter time guides
CALLOUT = (232, 168, 52)        # amber ring around the worked-example cell


# =============================================================================
# 1. Parse the flowline CSV
# =============================================================================
def parse_csv(path: Path):
    with path.open(encoding="utf-8") as fh:
        rows = list(csv.reader(fh))
    if not rows:
        sys.exit(f"empty CSV: {path}")
    weeks = [w.strip() for w in rows[0][1:] if w.strip()]
    nw = len(weeks)
    zones, grid = [], []
    for r in rows[1:]:
        if not r or not r[0].strip():
            continue
        zones.append(r[0].strip())
        cells = [(c.strip() or None) for c in r[1:1 + nw]]
        cells += [None] * (nw - len(cells))     # pad short rows
        grid.append(cells)

    # trim trailing weeks that are empty for every zone
    last = 0
    for c in range(nw):
        if any(grid[r][c] for r in range(len(zones))):
            last = c
    weeks = weeks[:last + 1]
    grid = [row[:last + 1] for row in grid]
    return zones, weeks, grid


def validate(grid, zones):
    used = {c for row in grid for c in row if c}
    unknown = used - set(WAGONS)
    if unknown:
        sys.exit(f"ERROR: CSV uses wagons not in the WAGONS legend table: {sorted(unknown)}\n"
                 f"       Add a (label, colour) for each in generate_takt_scheme.py, then re-run.")
    unused = set(WAGONS) - used
    if unused:
        print(f"WARNING: WAGONS table defines wagons absent from the CSV: {sorted(unused)}")


# =============================================================================
# 2. Rendering (Pillow, supersampled for anti-aliasing)
# =============================================================================
SS = 2

# layout (logical px)
W = 1300
PAD_L, PAD_R = 70, 30
TITLE_Y, SUB_Y = 30, 58
HEADER_Y = 84                    # week tick labels
GRID_Y0 = 100
CH = 26                          # cell height (one zone row)
LEGEND_COLS = 4
LEGEND_ROW_H = 26
SWATCH = 15


def sc(v):
    return v * SS


def hexcol(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def font_path(bold: bool) -> str:
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    p = FONT_DIR / name
    if p.exists():
        return str(p)
    try:  # fallback: borrow matplotlib's bundled copy
        import matplotlib
        mp = Path(matplotlib.__file__).parent / "mpl-data" / "fonts" / "ttf" / name
        if mp.exists():
            return str(mp)
    except Exception:
        pass
    sys.exit(f"font {name} not found in {FONT_DIR}")


def fnt(bold: bool, size: int):
    return ImageFont.truetype(font_path(bold), int(sc(size)))


def luminance(rgb):
    r, g, b = (c / 255 for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def render(zones, weeks, grid) -> Image.Image:
    nz, nw = len(zones), len(weeks)
    cw = (W - PAD_L - PAD_R) // nw                  # cell width to fit the span
    grid_w = cw * nw
    grid_x1 = PAD_L + grid_w
    grid_y1 = GRID_Y0 + CH * nz

    legend_y0 = grid_y1 + 40
    legend_rows = (len(WAGONS) + LEGEND_COLS - 1) // LEGEND_COLS
    note_y = legend_y0 + legend_rows * LEGEND_ROW_H + 8
    H = note_y + 30

    img = Image.new("RGBA", (int(sc(W)), int(sc(H))), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    f_title = fnt(True, 26)
    f_sub = fnt(False, 15)
    f_zone = fnt(True, 15)
    f_week = fnt(False, 12)
    f_leg = fnt(False, 13)
    f_note = fnt(False, 13)

    def text(xy, s, font, fill, anchor="lm", halo=False):
        kw = dict(stroke_width=int(sc(2)), stroke_fill=(255, 255, 255, 150)) if halo else {}
        d.text((sc(xy[0]), sc(xy[1])), s, font=font, fill=fill, anchor=anchor, **kw)

    # ---- title + subtitle ----------------------------------------------------
    text((PAD_L, TITLE_Y), "Example takt plan — flowline", f_title, INK_TITLE, anchor="lm")
    text((PAD_L, SUB_Y),
         f"{nz} takt zones × {nw} weekly takts · one coloured cell = one takt task "
         f"(wagon × zone × week) · from examples/takt-flowline-demo.csv",
         f_sub, INK, anchor="lm")

    # ---- time guides + week ticks (every 4th week, plus the last) ------------
    for c in range(nw):
        label_it = (c % 4 == 0) or (c == nw - 1)
        gx = PAD_L + c * cw
        if label_it:
            d.line([sc(gx), sc(GRID_Y0), sc(gx), sc(grid_y1)], fill=GUIDE, width=int(sc(1)))
            text((gx + cw / 2, HEADER_Y), weeks[c], f_week, INK, anchor="mm")

    # ---- row baselines + zone labels ----------------------------------------
    for r in range(nz + 1):
        gy = GRID_Y0 + r * CH
        d.line([sc(PAD_L), sc(gy), sc(grid_x1), sc(gy)], fill=GRID, width=int(sc(1)))
    d.line([sc(PAD_L), sc(GRID_Y0), sc(PAD_L), sc(grid_y1)], fill=GRID, width=int(sc(1)))
    d.line([sc(grid_x1), sc(GRID_Y0), sc(grid_x1), sc(grid_y1)], fill=GRID, width=int(sc(1)))
    for r, z in enumerate(zones):
        text((PAD_L - 8, GRID_Y0 + r * CH + CH / 2), z, f_zone, INK, anchor="rm")

    # ---- the coloured task cells (the flowline itself) ----------------------
    inset = 1.6
    for r in range(nz):
        for c in range(nw):
            wid = grid[r][c]
            if not wid:
                continue
            col = hexcol(WAGONS[wid][1])
            x0 = PAD_L + c * cw + inset
            y0 = GRID_Y0 + r * CH + inset
            x1 = PAD_L + (c + 1) * cw - inset
            y1 = GRID_Y0 + (r + 1) * CH - inset
            d.rounded_rectangle([sc(x0), sc(y0), sc(x1), sc(y1)], radius=int(sc(3)), fill=col)

    # ---- callout ring on the cell the worked A-Box models -------------------
    if CALLOUT_ZONE in zones and CALLOUT_WEEK in weeks:
        r = zones.index(CALLOUT_ZONE)
        c = weeks.index(CALLOUT_WEEK)
        x0 = PAD_L + c * cw - 1
        y0 = GRID_Y0 + r * CH - 1
        x1 = PAD_L + (c + 1) * cw + 1
        y1 = GRID_Y0 + (r + 1) * CH + 1
        d.rounded_rectangle([sc(x0), sc(y0), sc(x1), sc(y1)], radius=int(sc(4)),
                            outline=CALLOUT, width=int(sc(2.4)))
        # a little down-pointing marker above the cell
        mx, my = PAD_L + c * cw + cw / 2, GRID_Y0 - 7
        d.polygon([sc(mx - 5), sc(my - 6), sc(mx + 5), sc(my - 6), sc(mx), sc(my)], fill=CALLOUT)

    # ---- legend --------------------------------------------------------------
    col_w = (W - PAD_L - PAD_R) / LEGEND_COLS
    for i, (wid, (label, hx)) in enumerate(WAGONS.items()):
        cx = PAD_L + (i % LEGEND_COLS) * col_w
        cy = legend_y0 + (i // LEGEND_COLS) * LEGEND_ROW_H
        d.rounded_rectangle([sc(cx), sc(cy), sc(cx + SWATCH), sc(cy + SWATCH)],
                            radius=int(sc(3)), fill=hexcol(hx))
        text((cx + SWATCH + 8, cy + SWATCH / 2), f"{wid}  {label}", f_leg, INK, anchor="lm")

    # ---- footer note linking to the worked A-Box ----------------------------
    d.polygon([sc(PAD_L), sc(note_y - 5), sc(PAD_L + 10), sc(note_y - 5), sc(PAD_L + 5), sc(note_y + 1)],
              fill=CALLOUT)
    text((PAD_L + 18, note_y - 2),
         f"= {CALLOUT_ZONE} @ {CALLOUT_WEEK} (wagon 5.1) — the cell modelled end-to-end in "
         f"examples/takt-flowline-demo-b5-1.ttl",
         f_note, INK, anchor="lm")

    return img.resize((W, H), Image.LANCZOS)


# =============================================================================
# 3. README sync
# =============================================================================
def update_readme(rel_png):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    alt = "Example takt plan — flowline scheme generated from the demo data"
    block = f"{MARK_START}\n\n![{alt}]({rel_png})\n\n{MARK_END}"
    if MARK_START in text and MARK_END in text:
        new = text.split(MARK_START)[0] + block + text.split(MARK_END, 1)[1]
    elif ONTOLOGY_END in text:                       # place it just below the ontology diagram
        i = text.index(ONTOLOGY_END) + len(ONTOLOGY_END)
        new = text[:i] + "\n\n" + block + text[i:]
    else:
        print("note: README has neither TAKT-SCHEME nor ONTOLOGY-DIAGRAM markers; not modified.")
        return
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"updated README takt-scheme block -> {rel_png}")
    else:
        print("README already up to date.")


# =============================================================================
def main():
    if not CSV.exists():
        sys.exit(f"flowline CSV not found: {CSV}")
    zones, weeks, grid = parse_csv(CSV)
    validate(grid, zones)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    img = render(zones, weeks, grid)
    img.save(OUT, "PNG", optimize=True)
    rel = OUT.relative_to(ROOT).as_posix()
    print(f"wrote {rel}  ({img.size[0]}x{img.size[1]}, {len(zones)} zones, "
          f"{len(weeks)} weeks, {len(WAGONS)} wagons)")

    update_readme(rel)


if __name__ == "__main__":
    main()
